### ISSUE TITLE
Ship jar file in zipped release

### ISSUE THREAD

**Issue by circa10a** [enoviti/sonar-gosu#3]
It would be faster/easier for users to download the jar directly rather than compile it. If this could be included in the zip created by the release or another URL be included somewhere, it would be very helpful.

**Comment by sfgroups-k8s** [comment]
Not able to compile the source code, I am also looking for pre-build jar file.

**Comment by circa10a** [comment]
I was able to build just fine. Pre-built would just be a nice to have.

**Comment by MuhammadFarooq1234** [comment]
Can I ask how you were able to build the jar file? I compiled the entire project into a jar and sonarqube does not even start.

**Comment by circa10a** [comment]
`mvn clean install`
Then got the snapshot jar file in the `target` directory. 
Although I wouldn't waste any time with it. I have yet to get the plugin to successfully work. See #1
