### ISSUE TITLE
Gosu plugin installed, but only running two rules

### ISSUE THREAD

**Issue by westwoodad** [enoviti/sonar-gosu#6]
Hi,

We appear to have the plugin running, it is analysing the Gosu source and the results are being pushed to SonarQube. The only issue is that it is only running two rules, which aren't really that helpful (%comments and duplicated code).

Is there any reason why it would only run two rules? Is there a dependency that I cannot see, or is there a way I find the issue with the other rules?

Thanks, Andrew.

**Comment by abhijay94** [comment]
@westwoodad Which version of SonarCube did you use?
